### ISSUE TITLE
如何使用HTTP不安全内容

### ISSUE THREAD

**Issue by wosiwq** [Alive24/pcr-clan-battle-analyzer-vue#1]
如题 readme里面写到要用以下两步就戛然而止了

**Comment by Alive24** [comment]
PCRBOT域名地址(可以使用http协议，适合机器人地址是ip的用户)：[http://clan-battle-analyzer.pcrbot.com/]
(最新版的yobot已经将入口内嵌，详见该[commit](https://github.com/pcrbot/yobot/commit/2fbfc3b519fb33577bc0dffe0c6058c8214722a9))
