### ISSUE TITLE
权重计分的修正权重怎么才能生效？

### ISSUE THREAD

**Issue by isaac1216** [Alive24/pcr-clan-battle-analyzer-vue#3]
第四项权重计分分析里我修改过权重，实际倍率显示也有变动，但是分析时仍是按照默认倍率算分，尝试过先修改权重后分析，和先分析后修改权重，都没有生效。

最后很感谢大佬的数据分析网站，现在更容易刀内鬼了233

**Comment by isaac1216** [comment]
本意是调高龙的计分倍率，降低马的计分倍率，筛出一些毛分怪，毕竟一堆人抢马但是很少人打龙。

**Comment by Alive24** [comment]
我看了下，可能是我的二周目算法没弄好，当时可能只检查了一周目的算法有效，我看看尽快发个新的commit

**Comment by Alive24** [comment]
感谢支持hhhhhhhhh

**Comment by Alive24** [comment]
新commit应该已经修正好了，手动测试了一下
https://github.com/Alive24/pcr-clan-battle-analyzer-vue/commit/9664df1bad307571e857da148f16d06e423c4fcb

**Comment by isaac1216** [comment]
> 新commit应该已经修正好了，手动测试了一下
> [9664df1](https://github.com/Alive24/pcr-clan-battle-analyzer-vue/commit/9664df1bad307571e857da148f16d06e423c4fcb)

已可用，感谢！
