### ISSUE TITLE
能否添加按时间筛选刀的功能

### ISSUE THREAD

**Issue by beast27** [Alive24/pcr-clan-battle-analyzer-vue#4]
无法按月选择会战分析数据，两次会战打完后每个成员统计到的有效刀已经有三十刀左右了，导致分析不能得到准确的结果。请问除了每个月删掉上个月的数据之外有什么办法吗？

**Comment by wosiwq** [comment]
切换档案
在[我的公会]-[设置]选项中 最下面会有[切换档案]的按钮
每个月会战结束后开一个新档案即可
例：
![image](https://user-images.githubusercontent.com/45610776/98509638-85cd5100-229c-11eb-8e1b-2f25d6e65d67.png)
将图中[切换至]选项中的数字切换为没有档案的数字 本图中已有数据的是0号存档 遂点击加号切换为1号存档 确定即可

**Comment by Alive24** [comment]
如果会战机器人更新了就可以解决问题的话，我这边就不做开发计划了【虽然原本也没有那么多人反映这个需求，所以没有做。

**Comment by beast27** [comment]
我懂了，憨憨会长每次开会战只会修改boss状态没有开新档，谢谢。
